apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  log.override: |
   log

  contoso.server: |
    contoso.local:53 {
        errors
        log
        cache 30
        forward contoso.local 192.168.199.5  # this is the domain controller on-premise. If you are using a custom IP, change this file to match IP of domain controller dc1
    }