apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  log.override: |
   log

  contoso.server: |
    contoso.local:53 {
        errors
        log
        cache 30
        forward . 192.168.199.5  # this is my test/dev DNS server
    }