jobs:
  - job:
    steps:
      
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --name $(Build.BuildNumber) \
            --resource-group $(ResourceGroupName) \
            --template-file aks/bicep/aks/pipelines/azure-pipelines.yml \ 
            --parameters environmentType=$(EnvironmentType) deployToyManualsStorageAccount=$(DeployToyManualsStorageAccount)