jobs:
  - job:
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --name $(Build.BuildNumber) \
            --template-file aks/bicep/aks/pipelines/azure-pipelines.yml \ 
            --parameters adUserId=$(adUserId) ResourceGroupName=$(ResourceGroupName_pbk) networkPlugin=$(NetworkPlugin_kubenet) aksPrivatePublic=$(aksPrivatePublic_pbl)