trigger: 
  batch: true
  branches:
    include:
      - aks

  paths:
    include:
      - bicep/aks/main.bicep
      - bicep/aks/modules/*
      - bicep/aks/scripts/*
jobs:
  - job:
    timeoutInMinutes: 120 
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --name $(Build.BuildNumber)-public-kubenet \
            --location $(location) \
            --template-file bicep/aks/main.bicep \
            --parameters ADUserID=$(adUserId) ResourceGroupName=$(ResourceGroupName_pbk) KubenetOrCNINetworkPolicy=$(NetworkPlugin_kubenet) PublicOrPrivateCluster=$(aksPrivatePublic_pbl)

  - job:
    timeoutInMinutes: 120
    steps:
      
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName)
        
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --name $(Build.BuildNumber)-private-kubenet \
            --location $(location) \
            --template-file bicep/aks/main.bicep \
            --parameters ADUserID=$(adUserId) ResourceGroupName=$(ResourceGroupName_prv) KubenetOrCNINetworkPolicy=$(NetworkPlugin_kubenet) PublicOrPrivateCluster=$(aksPrivatePublic_prv)

  - job:
    timeoutInMinutes: 120
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --name $(Build.BuildNumber)-public-cni \
            --location $(location) \
            --template-file bicep/aks/main.bicep \
            --parameters ADUserID=$(adUserId) ResourceGroupName=$(ResourceGroupName_cpb) KubenetOrCNINetworkPolicy=$(NetworkPlugin_CNI) PublicOrPrivateCluster=$(aksPrivatePublic_pbl)

  - job:
    timeoutInMinutes: 120
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --name $(Build.BuildNumber)-private-cni \
            --location $(location) \
            --template-file bicep/aks/main.bicep \
            --parameters ADUserID=$(adUserId) ResourceGroupName=$(ResourceGroupName_cpr) KubenetOrCNINetworkPolicy=$(NetworkPlugin_CNI) PublicOrPrivateCluster=$(aksPrivatePublic_prv)