trigger: none
  
jobs:
  - job:
    timeoutInMinutes: 120 
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --name $(Build.BuildNumber)-public-kubenet \
            --location $(location) \
            --template-file aks/json/aks-kubenet.json \
            --parameters ADUserID=$(adUserId) KubenetOrCNINetworkPolicy=kubenet PublicOrPrivateCluster=public

  - job:
    timeoutInMinutes: 120
    steps:
      
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName)
        
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --name $(Build.BuildNumber)-private-kubenet \
            --location $(location) \
            --template-file aks/json/aks-private.json \
            --parameters ADUserID=$(adUserId) KubenetOrCNINetworkPolicy=kubenet PublicOrPrivateCluster=private

  - job:
    timeoutInMinutes: 120
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --name $(Build.BuildNumber)-public-cni \
            --location $(location) \
            --template-file aks/json/aks-cni.json \
            --parameters ADUserID=$(adUserId) KubenetOrCNINetworkPolicy=CNI PublicOrPrivateCluster=public

  - job:
    timeoutInMinutes: 120
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ServiceConnectionName)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --name $(Build.BuildNumber)-private-cni \
            --location $(location) \
            --template-file aks/json/aks-cni.json \
            --parameters ADUserID=$(adUserId) KubenetOrCNINetworkPolicy=CNI PublicOrPrivateCluster=private