apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: colors-fanout-ingress-nginx
  namespace: colors-ns
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: akscolors.penguintrails.com
      http:
        paths:
          - path: /red
            backend:
              serviceName: red-service-cluster-ip
              servicePort: 8080
          - path: /green
            backend:
              serviceName: green-service-cluster-ip
              servicePort: 8080
          - path: /blue
            backend:
              serviceName: blue-service-cluster-ip
              servicePort: 8080
          - path:
            backend:
              serviceName: red-service-cluster-ip
              servicePort: 8080
